service: bice-vida-lab-test

provider:
  name: aws
  runtime: nodejs12.x

# serverless-offline requires node.js version 10.13.0 or higher
# Comment the next "- serverless-offline" line if you have a lower version
plugins:
  - serverless-offline

functions:
  policy:
    handler: index.policy
    events:
     - http:
         path: /interview/insurance/policy/costs
         method: get